# Generated by Django 4.1.7 on 2023-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drugs', 'Лекарственные средства'), ('vitamins', 'Витамины и БАДы'), ('medical', 'Изделия медицинского назначения'), ('mother', 'Мать и Дитя'), ('medtech', 'Медтехника'), ('cosmetics', 'Косметика'), ('hygiene', 'Гигиена')], default='uncategorized', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=40),
        ),
    ]
