# Generated by Django 4.1.7 on 2023-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_product_category_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drugs', 'Дәрілік заттар'), ('vitamins', 'Витаминдер мен диеталық қоспалар'), ('medical', 'Медициналық мақсаттағы бұйымдар'), ('mother', 'Ана мен бала'), ('medtech', 'Медициналық техника'), ('cosmetics', 'Косметика'), ('hygiene', 'Гигиена')], default='uncategorized', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
